version: 2.1

executors:
  aebuilder:
    docker:
      - image: aeternity/builder
        user: builder
    working_directory: ~/src

jobs:
  build:
    executor: aebuilder
    steps:
      - checkout
      - restore_cache:
          keys:
            - dialyzer-cache-v1-{{ .Branch }}-{{ .Revision }}
            - dialyzer-cache-v1-{{ .Branch }}-
            - dialyzer-cache-v1-
      - run:
          name: Build
          command: make
      - run:
          name: Static Analysis
          command: rebar3 dialyzer
      - run:
          name: Eunit
          command: rebar3 eunit
      - run:
          name: Common Tests
          command: rebar3 ct
      - save_cache:
          key: dialyzer-cache-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - _build/default/rebar3_20.3.8_plt
      - store_artifacts:
          path: _build/test/logs
  docker_push_tag:
    executor: aebuilder
    environment:
      DOCKERHUB_REPO: aeternity/aesophia_http
    steps:
      - checkout
      - run:
          name: Build and push Docker image to DockerHub
          command: |
            docker build -t ${DOCKERHUB_REPO:?}:${CIRCLE_BRANCH:?} .

workflows:
  build_push:
    jobs:
      - build
      - docker_push_tag:
          requires:
            - build
          filters:
            branches:
              only: automatic-docker-hub-images-for-aesophia_http-PT-164530806
